<a href="https://colab.research.google.com/github/maritnorli/PyTorch-course/blob/main/00_PyTorch_basics_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello, learning PyTorch here!") #Shift+enter to run code

Hello, learning PyTorch here!


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


To do deep learning we need to change runtime by selecting a GPU under runtime> change runtime type > T4 GPU

In [ ]:

!nvidia-smi #to check what our GPU is


## Introduction to tensors
### Creating tensors
Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [ ]:
# scalar
scalar = torch.tensor(7) #make sure the cell with import torch has been run
scalar


tensor(7)

In [ ]:
scalar.ndim #gives 0 #how many dimensions it has

0

In [ ]:
# Get tensor back as Pyyhon int
scalar.item() #gives a tensor as integer


7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim #how many dimensions a vector has, this has 1 dimension. The number of square brackets in torch.tensor([]) is the number of dimensions


1

In [ ]:
vector.shape # shape is 2 by 1 = 2 elements for [7, 7]

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1] #index zero

tensor([ 9, 10])

In [ ]:
MATRIX.shape #is 2 by 2 = 4 elements for [[7, 8], [9,10]])

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4 , 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim #

3

In [ ]:
TENSOR.shape
#Gives torch.Size([1, 3, 3])
# the dimension order is 0, 1, 2
# is 1 by 3 by 3 so 9 elements
# this says we have one 3 by 3 tensor
# also matching up with bracets, so dim 0 is outer,first bracket,
# dim 1 is second bracket, dim 2 is third bracket
#tensor([[[1, 2, 3], <---dim 0
#         [3, 6, 9], <-- dim 1
#         [2, 4, 5]]]) <- dim 2
#tensor([--1, 2, 3-, <---dim 0 brackets
#         -3, 6, 9-,
#         -2, 4, 5--])
#tensor(-[-1, 2, 3-, <---dim 1 brackets
#         -3, 6, 9-,
#         -2, 4, 5-]-)
#tensor(--[1, 2, 3], <---dim 2 brackets
#         [3, 6, 9],
#         [2, 4, 5]--)


torch.Size([1, 3, 3])

In [ ]:
TENSOR[0] #index zero

###CODE CELL TO TEXT CELL IN COLAB IS ctrl+M+M

### Random tensors
Why random tensors?
Random tensors are important because the way many neurak networks learn is that they start with tensors full of random numbers and adjust those random numbers to better represent the data
`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors doc -
https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4) # this can be any number of dimensions ie (1, 3, 4)
random_tensor

tensor([[0.4509, 0.8131, 0.8974, 0.4425],
        [0.1670, 0.2024, 0.1268, 0.2047],
        [0.2554, 0.7694, 0.7609, 0.2761]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape as an image tensor
random_image_size_tensor = torch.rand(size=(3, 244, 244)) #color channels RGB, hight, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype # default data type is torch.float, this can be edited

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# use torch.range() #OBS torch.range to be removed in future release, so a way around is to
# use arange instead
torch.arange(0, 10)
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Colab trick to see documentation = SHIFT+TAB, but google it may work best

In [ ]:
#use steps
one_to_ten = torch.arange(start=1, end=1000, step=77)
one_to_ten
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor ie float 32 or 16
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

### Datatypes is important because of precision in computing, and IS ONE OF THE 3 BIG errors you'll run into WITH PYTORCH & DEEP LEARNING
numerical quantity
float32 usually occupies 32 bits in computer memory. 32 is single precision
float16 stores the number with 16 bit. 16 is half precision
If you can sacrifice precision you can calculate faster when using less memory

### Errors:
1. Tensors not right datatype
2. Tensors not right shape (MATRIX multiplication)
3. Tensors not on the right device ("cpu" or "cuda")

1. IE: Calculation crashes with trying to calculate with both 32 and 16
2.IE=Two matrixes not in the same shape multiplication does not work
3. If one tensor is on cpu and one on GPU it does not work



In [ ]:
# Dealing with error 1:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Important note is you didnt get an error here, but it could happen later on in the code

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.float32)
int_32_tensor

tensor([3., 6., 9.])

### Getting information from our tensors

Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
Tensors not right shape - to get shape from a tensor, use `tensor.shape`
Tensors not on the right device - to get device from a tensor, use `tensor.device`



In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3283, 0.5629, 0.9559, 0.8116],
        [0.4691, 0.2208, 0.7163, 0.7277],
        [0.0695, 0.0589, 0.3384, 0.1025]])

In [ ]:
some_tensor.size(), some_tensor.shape #used both to check size and shape is same


(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") #Could have used .size() too
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3283, 0.5629, 0.9559, 0.8116],
        [0.4691, 0.2208, 0.7163, 0.7277],
        [0.0695, 0.0589, 0.3384, 0.1025]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors  

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element -wise)
* division
* Matrix multiplication


In [ ]:
#Addition
#create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
#Multiply
tensor * 10

tensor([10, 20, 30])

In [ ]:
#Subtract
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch inbuilt functions
torch.mul(tensor, 10) #also have ie torch.add


tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplications in neural networks and deep learning
1. Element wise multiplication
2. Matrix Multiplication (dot product)

more info: mathisfun (matrix-multiplication)

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* `(3, *2*) @ (*3*, 2)`wont work
* `(2, *3*) @ (*3*, 2)`will work
* `(3, *2*) @ (*2*, 3)`will work
2. The resulting matrix has the shapes of the **outer dimensions**
* `(*2*, 3) @ (3, *2*)`-> (2, 2)
* `(*3*, 2) @ (2, *3*)`-> (3, 3)

`torch.matmul(torch.rand(3, 2), torch.rand(2, 3))`

In [ ]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[2.6661, 3.7099, 3.0934],
        [2.4210, 3.2754, 2.5855],
        [2.1040, 3.6758, 2.9170]])

In [ ]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3)).shape

torch.Size([3, 3])

In [ ]:
print(tensor)

tensor([1, 2, 3])


In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}") # = [1*1, 2*2, 3*3]


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor) #= 1*1 + 2*2 + 3*3 = [14]

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.57 ms, sys: 0 ns, total: 1.57 ms
Wall time: 1.47 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 346 µs, sys: 32 µs, total: 378 µs
Wall time: 318 µs


tensor(14)

One of the most common errors in deep learning: Shape errors

In [ ]:
#Shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) #torch.mm = torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix sesor shape issues, manipulate shape of tensor using Transpose
A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
# The matrix multiplication works when thensor:B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} same shape as above, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <-- inner dimensions must match")
print("Output:\n")
output= torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) same shape as above, tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <-- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find min
torch.min(x), x.min()



(tensor(0), tensor(0))

In [ ]:
# Find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find mean
torch.mean(x)


RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
x.dtype


torch.int64

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.argmin() #at what index we get the min value

tensor(0)

In [ ]:
x.argmax() #Find pos for max

tensor(9)

In [ ]:
x[0]

tensor(0)

In [ ]:
x[9]


tensor(91)

### Reshaping, stacking, squeezing and unsqueezing
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original
* Stacking - compine multiple tensors on top of each other (vstack) or side by side (torch.hstack)
torch.stack, torch.vstack, torch.hstack
* Squeeze - removes all `1`dimensions from a tensor
* Unsqueeze - add a `1`dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.


In [ ]:
# Crate a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add dimension
x_reshaped = x.reshape(1, 9) #note adding a bracket!!
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Add dimension and turn
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape
#same as: x_reshaped.T, x_reshaped.T.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
x= torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
x= torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
x_reshaped = x.reshape(3, 4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [ ]:
# Crate a tensor again
import torch
x = torch.arange(1., 10.)
x, x.shape
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Changing z changes x (because a view of a tensor shares the same memory as the Original)

In [ ]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
print(f"made a view z of x using z = x.view(1, 9)")
print(f"Changing z index[0] to 5: {z} \nalso changed the index [0] in x: {x}")

made a view z of x using z = x.view(1, 9)
Changing z index[0] to 5: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
also changed the index [0] in x: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
#x_stacked = torch.stack([x, x, x, x], dim=1) #play with this
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Squeeze and unsqueeze
# torch.squeeze() removes all single dimensions from a target tensor
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_squeezed = x_reshaped.squeeze()

In [ ]:
# torch.unsqueeze() # adds a single dimension to a target tensor
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#add an extra dim
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
#x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"New \ntensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New 
tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
#Permute means rearrange
x_original = torch.rand(size=(244, 244, 3)) #[dim 0= height, dim 1= width, dim 2= color_chan]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #color, height, width

print(f"Previous shape: {x_original.shape}")
print(f"Previous shape: {x_permuted.shape}")


Previous shape: torch.Size([244, 244, 3])
Previous shape: torch.Size([3, 244, 244])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.



In [ ]:
#Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index the tensor to outer bracket, to dim 0 [*1*, 3, 3]
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index the tensor to middle bracket, to dim 1 [1, *3*, 3]
x[0][0] # same as x[0, 0]

tensor([1, 2, 3])

In [ ]:
# Index the tensor to inner bracket, to dim 2 [1, 3, *3*]
x[0][0][0] # same as x[0, 0, 0]

tensor(1)

In [ ]:
# Index the tensor to inner bracket, to dim 2 [1, 3, *3*]
x[0][1][1] # shoud get 5 # same as x[0, 1, 1]

tensor(5)

In [ ]:
# Use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0th and 1st dimensions but only the 1 index of 1st 2nd dimension
x[:, 1, 1] # OBS gives almost the same as x[0,1,1], but keeps all of 0 dim


tensor([5])

In [ ]:
# Get index 0 of 0th dimension and all values of second dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#index on x to get 9:
x[0,2,2]

tensor(9)

In [ ]:
#index on x to get 3 , 6, 9
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors & NumPy
Pytorch interacts with numpy
* Data in NumPy, want PyTorch tensor -> `torch.from_numpy(ndarray)`
*PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #can change dtype with type(torch.float32)
array, array.dtype, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will it do to `tensor`?
array = array + 1
array, tensor
 # DOES NOT change it


(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() #OBS. This time numpy dtype reflects the tensor default dtype = float32
tensor, tensor.dtype, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to ´numpy_tensor´
tensor = tensor + 1
tensor, numpy_tensor
# DOES NOT change it

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibiliy (trying to take random out of random)
In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better represent the data -> again -> again -> again ... `

if we do
torch.rand(3, 3)

#every single time its run the random numbers change.
#how can we reduce the randomness in neural networks and pytorch
by **random seed**

Essentially it flavours the randomness.

check pytorch doc randomness
wikipedia: random seed



In [ ]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"random_tensor_A: \n{random_tensor_A}")
print(f"random_tensor_B: \n{random_tensor_B}")
print(f" 1==1 = {1==1}")
print(f"random_tensor_A == random_tensor_B =")
print(random_tensor_A == random_tensor_B)



random_tensor_A: 
tensor([[0.9649, 0.4867, 0.0533, 0.3496],
        [0.4824, 0.4981, 0.9026, 0.6860],
        [0.2644, 0.8122, 0.7173, 0.9782]])
random_tensor_B: 
tensor([[0.3017, 0.7089, 0.7932, 0.4022],
        [0.2303, 0.2508, 0.7655, 0.9495],
        [0.5660, 0.8386, 0.1323, 0.9216]])
 1==1 = True
random_tensor_A == random_tensor_B =
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Make som random but reproducable tensors
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED) # had to set this both times we called the random method
random_tensor_D = torch.rand(3, 4)

print(f"random_tensor_C: \n{random_tensor_C}")
print(f"random_tensor_D: \n{random_tensor_D}")
print(f" 1==1 = {1==1}")
print(f"random_tensor_C == random_tensor_D =")
print(random_tensor_C == random_tensor_D)


random_tensor_C: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
random_tensor_D: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
 1==1 = True
random_tensor_C == random_tensor_D =
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensorrs and PyTorch objects on the GPUs (and making faster computations)
GPUs = faster computation thanks to cuda + nvidia hardware + pytorch working behind the scenes

### 1. Getting a GPU
1. Easiest - use google colab for a free GPU. or colab pro 10dollar/month
2. Use own GPU - takes setup and investments of setting it up
  google: which GPU is best for deep learning
3. Use cloud computing GCP, AWS, Azure. allow you to rent computers on the cloud and access them.

For 2, 3 Pytorch + GPU drivers (cuda) takes setting it up


In [ ]:
### Connect to GPU:
!nvidia-smi


Thu Feb 22 14:39:55 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
### Check for GPU access with PyTorch
import torch
torch.cuda.is_available()


True

For Pytorch since its capable of running compute on the GPU or CPU, its best practice to setup device agnostic code

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [ ]:
# count number of gpus to use
torch.cuda.device_count()

1

## 3. Puttimg tensors and models on the GPU
The reason we want our tensors/models on our GPU is because GPU results in faster computations


In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if availiable)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
### 4. Moving tensors back to the cpu


In [ ]:
# If tensor is on GPU, cant transfor it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#To fix the GPU tensor with numpy issue, we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

## Exercises & Extra curriculum